// Functional browser tests. All financial records and credentials are fictitious; external traffic is blocked.
const {createRequire}=require('node:module');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
const req=process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?createRequire(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright/package.json')):require;
const {chromium}=req('playwright');
const root=path.resolve(process.env.AUDIT_PROJECT||'.'),out=path.resolve(process.env.AUDIT_OUTPUT||path.join(root,'verificacion/evidencias/release'));
const base='http://127.0.0.1:4173',user={usuarioId:'usr_gustavo',nombre:'Cuenta de prueba',workspaceId:'ws_audit',workspaceNombre:'Espacio de prueba'};
const catalogos={categorias:[{categoria_id:'cat_bancon',nombre:'Banco de prueba',color:'#b39bff'}],formasPago:[{forma_pago_id:'fp_manual',nombre:'Manual'},{forma_pago_id:'fp_debito_automatico',nombre:'Débito automático'}],servicios:[],fuentesIngreso:[],parametros:[{clave:'tipo_cambio_default',valor:1000}],mediosPago:[{medio_pago_id:'mp_bancon',nombre:'Banco de prueba',tipo:'banco',color:'#b39bff'}],instrumentosPago:[{instrumento_id:'ins_manual',nombre:'Manual',tipo:'manual'},{instrumento_id:'ins_debito_automatico',nombre:'Débito automático',tipo:'automatico'},{instrumento_id:'ins_tarjeta_credito',nombre:'Tarjeta de crédito',tipo:'tarjeta'}],categoriasGasto:[{categoria_gasto_id:'cg_servicios',nombre:'Servicios',color:'#a78bfa'}],etiquetas:[],conceptoEtiquetas:[],conceptos:[]};
function expense(id,name,amount,period='2026-10',extra={}){return {movimiento_id:id,tipo_movimiento:'GASTO',subtipo_movimiento:'GASTO',periodo:period,dia:1,concepto_manual:name,monto:amount,moneda:'ARS',estado:'pendiente',vencimiento:period+'-10',medio_pago_id:'mp_bancon',medio_pago_nombre:'Banco de prueba',instrumento_id:'ins_manual',instrumento_nombre:'Manual',forma_pago_nombre:'Manual',categoria_id:'cat_bancon',categoria_gasto_id:'cg_servicios',workspace_id:'ws_audit',activo:true,...extra};}
function income(id,amount,period='2026-10',salary=false){return {movimiento_id:id,tipo_movimiento:'INGRESO',subtipo_movimiento:salary?'SUELDO':'INGRESO_EXTRA',periodo:period,dia:2,concepto_manual:'Ventas de prueba',monto:amount,moneda:'ARS',estado:'pagado',workspace_id:'ws_audit',activo:true};}
const initial=()=>[
 expense('internet','Internet',15000,'2026-10',{instrumento_id:'ins_debito_automatico',instrumento_nombre:'Débito automático',forma_pago_nombre:'Débito automático',vencimiento:'2026-10-05',es_recurrente:true}),
 expense('rent','Alquiler',100000,'2026-10',{estado:'pagado',es_recurrente:true}),
 expense('light','Luz',12000,'2026-10',{vencimiento:'2026-10-04'}),
 expense('gym','Gimnasio',8000,'2026-10',{requiere_revision:true,motivo_revision:'REVISAR_MONTO_VENCIMIENTO',origen_movimiento:'REPLICA_MES',es_recurrente:true}),
 ...[['Internet',12000],['Alquiler',90000],['Luz',10000],['Gimnasio',8000]].map(([n,a],i)=>expense('prev_'+i,n,a,'2026-09',{estado:'pagado'})),
 expense('next_internet','Internet',15000,'2026-11',{instrumento_id:'ins_debito_automatico',instrumento_nombre:'Débito automático',forma_pago_nombre:'Débito automático',requiere_revision:true,origen_movimiento:'REPLICA_MES'}),
 income('salary',200000,'2026-10',true),income('income',50000),income('old_salary',200000,'2026-09',true),income('old_income',25000,'2026-09')
];
let browser,server,contexts=[],results=[];
async function setup({authenticated=true,width=390,records=initial(),clock='2026-10-05T12:00:00-03:00'}={}){
 const context=await browser.newContext({viewport:{width,height:844},timezoneId:'America/Argentina/Buenos_Aires',locale:'es-AR',serviceWorkers:'block',acceptDownloads:true});contexts.push(context);
 const page=await context.newPage();page.setDefaultTimeout(7000);await page.clock.setFixedTime(new Date(clock));
 await page.addInitScript(({authenticated,user})=>{if(!sessionStorage.getItem('initialized')){sessionStorage.setItem('initialized','yes');if(authenticated){localStorage.setItem('mf_auth_token','fictional-token');localStorage.setItem('mf_auth_user',JSON.stringify(user));localStorage.setItem('gapp_v7',JSON.stringify({old:'fictitious old cache'}));}}},{authenticated,user});
 const state={db:structuredClone(records),requests:[],errors:[],failNext:null,failReadAfterWrite:false,readFailure:false},send=(r,data,status=200)=>r.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});
 page.on('pageerror',e=>state.errors.push(e.message));
 await context.route('**/*',async route=>{
  const request=route.request(),url=new URL(request.url());if(url.origin!==base)return route.abort();if(!url.pathname.startsWith('/api/'))return route.continue();
  const method=request.method(),body=request.postData()?request.postDataJSON():{},entry={path:url.pathname,method,body,period:url.searchParams.get('periodo')};state.requests.push(entry);
  if(state.failNext===url.pathname && method!=='GET'){state.failNext=null;return send(route,{ok:false,error:'Error de prueba. Volvé a intentarlo.'},503);}
  if(url.pathname==='/api/auth-login')return body.pin==='clave-prueba'?send(route,{ok:true,data:{token:'fictional-token',user:{...user,nombre:body.usuarioId==='otra'?'Otra cuenta':'Cuenta de prueba'}}}):send(route,{ok:false,error:'Usuario o clave incorrectos'},401);
  if(url.pathname==='/api/catalogos')return send(route,{ok:true,data:catalogos});
  if(url.pathname==='/api/movimientos'){if(state.readFailure)return send(route,{ok:false,error:'Error de conexión de prueba'},503);return send(route,{ok:true,data:{movimientos:state.db.filter(m=>!entry.period||m.periodo===entry.period),detalles:[],etiquetas:[]}});}
  if(url.pathname==='/api/cotizaciones')return send(route,{ok:true,data:{valor:1000,fuente:'prueba'}});
  if(method!=='GET'){
   await new Promise(r=>setTimeout(r,80));
   let id=body.movimientoId||body.id;
   if(url.pathname==='/api/gastos'||url.pathname==='/api/gastos-update'){
    if(!id)id='new_'+state.requests.length;
    const item=expense(id,body.servicio,body.monto,body.periodo,{dia:Number(body.dia),concepto_id:body.conceptoId||null,moneda:body.moneda,estado:body.estado,vencimiento:body.vencimiento,observacion:body.observacion,medio_pago_id:body.medioPagoId,instrumento_id:body.instrumentoId,instrumento_nombre:body.instrumentoId==='ins_debito_automatico'?'Débito automático':'Manual',forma_pago_nombre:body.formaPago,requiere_revision:body.requiereRevision,motivo_revision:body.motivoRevision,origen_movimiento:body.origenMovimiento,es_recurrente:body.esRecurrente});
    if(url.pathname.endsWith('update'))state.db=state.db.map(m=>m.movimiento_id===id?item:m);else state.db.push(item);
   }else if(url.pathname==='/api/gastos-estado')state.db=state.db.map(m=>m.movimiento_id===id?{...m,estado:body.estado,...(body.estado==='pagado'?{requiere_revision:false,motivo_revision:null}:{})}:m);
   else if(url.pathname==='/api/gastos-delete'||url.pathname==='/api/ingresos-delete')state.db=state.db.filter(m=>m.movimiento_id!==id);
   else if(url.pathname==='/api/ingresos'){
    if(!id)id='income_'+state.requests.length;
    const item={...income(id,body.monto,body.periodo),concepto_manual:body.fuente,dia:body.dia};if(method==='PUT')state.db=state.db.map(m=>m.movimiento_id===id?item:m);else state.db.push(item);
   }else if(url.pathname==='/api/sueldo'){
    const existing=state.db.find(m=>m.periodo===body.periodo&&m.subtipo_movimiento==='SUELDO');id=existing?.movimiento_id||'salary_'+body.periodo;
    if(method==='DELETE')state.db=state.db.filter(m=>!(m.periodo===body.periodo&&m.subtipo_movimiento==='SUELDO'));
    else if(existing)existing.monto=body.monto;else state.db.push(income(id,body.monto,body.periodo,true));
   }
   if(state.failReadAfterWrite)state.readFailure=true;
   return send(route,{ok:true,data:{movimiento_id:id}});
  }
  return send(route,{ok:false,error:'Ruta no prevista'},404);
 });
 await page.goto(base);await page.waitForLoadState('networkidle');return {context,page,state};
}
const nav=async(p,label)=>{
 if(label==='Ajustes')return p.getByRole('button',{name:'Ajustes',exact:true}).click();
 if(label==='Ingresos'){await p.locator('.ni').filter({hasText:'Movimientos'}).click();return p.getByRole('button',{name:'Ingresos',exact:true}).click();}
 if(label==='Evolución'){await nav(p,'Informes');return p.getByRole('button',{name:'Evolución',exact:true}).click();}
 return p.locator('.ni').filter({hasText:label}).click();
};
async function noError(s){assert.deepEqual(s.state.errors,[]);}
async function probe(id,title,run){if(process.env.AUDIT_ONLY&&!process.env.AUDIT_ONLY.split(',').includes(id))return;try{await run();results.push({id,title,status:'correcto'});}catch(e){results.push({id,title,status:'fallo',error:String(e.stack)});}console.log(id,results.at(-1).status,results.at(-1).error?.slice(0,350)||'');for(const c of contexts)await c.close();contexts=[];await fs.writeFile(path.join(out,'results.json'),JSON.stringify(results,null,2));}
async function addExpense(s,name='Seguro de prueba',automatic=false){await nav(s.page,'Cargar');await s.page.locator('#expense-concept').fill(name);await s.page.locator('#expense-amount').fill('18000');await s.page.locator('#expense-account').selectOption('mp_bancon');if(automatic){await s.page.getByRole('checkbox',{name:/Débito automático/}).check();await s.page.locator('#expense-due').fill('2026-10-20');}else await s.page.locator('#expense-method').selectOption('ins_manual');}
(async()=>{
 await fs.mkdir(out,{recursive:true});const {createServer}=await import(pathToFileURL(path.join(root,'node_modules/vite/dist/node/index.js')));server=await createServer({root,server:{host:'127.0.0.1',port:4173,strictPort:true}});await server.listen();
 const mod=process.env.AUDIT_CHROMIUM_MODULE?require(process.env.AUDIT_CHROMIUM_MODULE):null,bundled=mod?.default||mod;
 browser=await chromium.launch({headless:true,...(bundled?{executablePath:process.env.AUDIT_BROWSER_EXECUTABLE,args:bundled.args.filter(x=>x!=='--single-process')}:{args:['--no-sandbox']})});
 await probe('UI-01','Login individual con error claro y recuperación',async()=>{const s=await setup({authenticated:false});await s.page.locator('#login-user').fill('gustavo');await s.page.locator('#login-pin').fill('incorrecta');await s.page.getByRole('button',{name:'Ingresar',exact:true}).click();await s.page.getByRole('alert').filter({hasText:'Usuario o clave incorrectos'}).waitFor();assert.equal(await s.page.getByText('Tu sesión venció',{exact:false}).count(),0);await s.page.locator('#login-pin').fill('clave-prueba');await s.page.getByRole('button',{name:'Ingresar',exact:true}).click();await s.page.locator('.balance-card').waitFor();await noError(s);});
 await probe('UI-02','Pantallas de 320, 390 y 1280 px sin desbordes ni errores',async()=>{for(const width of [320,390,1280]){const s=await setup({width});for(const view of ['Inicio','Movimientos','Cargar','Vencimientos','Informes','Evolución','Ingresos','Ajustes']){await nav(s.page,view);await s.page.waitForTimeout(60);const dimensions=await s.page.evaluate(()=>({body:document.documentElement.scrollWidth,view:innerWidth}));assert.ok(dimensions.body<=dimensions.view+1,`${view} ${width}: ${JSON.stringify(dimensions)}`);if(width===390)await s.page.screenshot({path:path.join(out,view.toLowerCase()+'.png'),fullPage:true});}await noError(s);}});
 await probe('UI-03','Gasto automático: alta pendiente, edición, cancelar borrado y eliminación',async()=>{const s=await setup();await addExpense(s,'Seguro de prueba',true);await s.page.getByRole('button',{name:'Guardar gasto',exact:true}).click();await s.page.waitForFunction(()=>document.querySelector('#expense-concept')?.value==='');const created=s.state.db.find(m=>m.concepto_manual==='Seguro de prueba');assert.equal(created.estado,'pendiente');assert.equal(created.instrumento_id,'ins_debito_automatico');await nav(s.page,'Movimientos');let row=s.page.locator('.movement-row').filter({hasText:'Seguro de prueba'});await row.getByRole('button',{name:'Editar',exact:true}).click();await s.page.getByRole('dialog').locator('#expense-amount').fill('19000');await s.page.getByRole('button',{name:'Guardar cambios',exact:true}).click();await s.page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(s.state.db.find(m=>m.movimiento_id===created.movimiento_id).monto,19000);await row.getByRole('button',{name:'Eliminar Seguro de prueba',exact:true}).click();await s.page.getByRole('button',{name:'Cancelar',exact:true}).click();assert.ok(s.state.db.some(m=>m.movimiento_id===created.movimiento_id));await row.getByRole('button',{name:'Eliminar Seguro de prueba',exact:true}).click();await s.page.getByRole('dialog').getByRole('button',{name:'Eliminar',exact:true}).click();await row.waitFor({state:'hidden'});assert.ok(!s.state.db.some(m=>m.movimiento_id===created.movimiento_id));await noError(s);});
 await probe('UI-04','Ingreso: guardar, editar y borrar con reintento tras error',async()=>{const s=await setup();await nav(s.page,'Ingresos');await s.page.locator('#income-source').fill('Reintegro de prueba');await s.page.locator('#income-amount').fill('3000');await s.page.getByRole('button',{name:'Registrar ingreso',exact:true}).dblclick();await s.page.waitForFunction(()=>document.querySelector('#income-source').value==='');assert.equal(s.state.requests.filter(r=>r.path==='/api/ingresos'&&r.method==='POST').length,1);const row=s.page.locator('.income-item').filter({hasText:'Reintegro de prueba'});await row.getByRole('button',{name:'Editar',exact:true}).click();await s.page.locator('#income-amount').fill('3500');await s.page.getByRole('button',{name:'Guardar cambios',exact:true}).click();await s.page.waitForFunction(()=>document.querySelector('#income-source').value==='');assert.equal(s.state.db.find(m=>m.concepto_manual==='Reintegro de prueba').monto,3500);s.state.failNext='/api/ingresos-delete';await row.getByRole('button',{name:'Eliminar',exact:true}).click();await s.page.getByRole('dialog').getByRole('button',{name:'Eliminar',exact:true}).click();await s.page.getByRole('dialog').getByRole('alert').waitFor();await s.page.getByRole('dialog').getByRole('button',{name:'Eliminar',exact:true}).click();await row.waitFor({state:'hidden'});await noError(s);});
 await probe('UI-05','Sueldo: actualizar y eliminar sin tocar otros meses',async()=>{const s=await setup();await nav(s.page,'Ingresos');await s.page.locator('#salary-amount').fill('250000');await s.page.getByRole('button',{name:'Actualizar',exact:true}).click();await s.page.waitForFunction(()=>document.querySelector('.income-salary').textContent.includes('250.000'));await s.page.locator('.income-salary').getByRole('button',{name:'Eliminar',exact:true}).click();await s.page.getByRole('dialog').getByRole('button',{name:'Eliminar',exact:true}).click();await s.page.locator('.income-salary').waitFor({state:'hidden'});assert.ok(s.state.db.some(m=>m.movimiento_id==='old_salary'));assert.ok(!s.state.db.some(m=>m.movimiento_id==='salary'));await noError(s);});
 await probe('UI-06','Informes: diferencia y porcentaje total y por concepto',async()=>{const s=await setup();await nav(s.page,'Informes');const text=await s.page.locator('.month-comparison').innerText();assert.ok(text.includes('15.000')&&text.includes('+12,5%'),text);const internet=await s.page.locator('.ranking-row').filter({hasText:'Internet'}).innerText();assert.ok(internet.includes('3.000')&&internet.includes('+25%'),internet);assert.ok(text.includes('en curso'));await nav(s.page,'Ingresos');const incomeText=await s.page.locator('.month-comparison').innerText();assert.ok(incomeText.includes('25.000')&&incomeText.includes('+11,1%'),incomeText);await noError(s);});
 await probe('UI-07','Débito vencido pide verificar y se conserva al pagar/deshacer',async()=>{const s=await setup();await nav(s.page,'Vencimientos');const auto=s.page.locator('.due-item').filter({hasText:'Internet'}).filter({hasText:'2026-10'});await auto.getByText('Verificar débito · hoy',{exact:true}).waitFor();await auto.getByRole('button',{name:'Confirmar débito',exact:true}).click();await auto.waitFor({state:'hidden'});await nav(s.page,'Movimientos');await s.page.getByRole('button',{name:'Débito automático',exact:true}).click();const row=s.page.locator('.movement-row').filter({hasText:'Internet'});await row.getByText('Pagado',{exact:true}).waitFor();await row.getByText('Débito automático',{exact:true}).waitFor();await row.getByRole('button',{name:'Marcar pendiente: Internet',exact:true}).click();await row.getByText('Verificar débito · hoy',{exact:true}).waitFor();assert.equal(s.state.db.find(m=>m.movimiento_id==='internet').instrumento_id,'ins_debito_automatico');await noError(s);});
 await probe('UI-08','Réplica hacia un mes parcialmente cargado sin repetir existentes',async()=>{const s=await setup();await s.page.getByRole('button',{name:/Replicar gastos/}).click();await s.page.getByRole('dialog').waitFor();assert.equal(await s.page.getByRole('dialog').getByText('Internet',{exact:true}).count(),0);await s.page.getByRole('button',{name:'Seleccionar todos',exact:true}).click();await s.page.getByRole('button',{name:/Continuar con 3/}).click();await s.page.getByRole('button',{name:'Confirmar copia',exact:true}).dblclick();await s.page.getByRole('heading',{name:'3 gastos copiados',exact:true}).waitFor();const target=s.state.db.filter(m=>m.periodo==='2026-11');assert.equal(target.length,4);for(const m of target){assert.equal(m.estado,'pendiente');assert.equal(m.requiere_revision,true);}assert.equal(target.filter(m=>m.concepto_manual==='Internet').length,1);await s.page.getByRole('button',{name:'Revisar Noviembre',exact:true}).click();await s.page.getByText('Confirmar importe y fecha',{exact:true}).first().waitFor();await s.page.getByRole('button',{name:'Mes anterior',exact:true}).click();await s.page.getByRole('button',{name:/Replicar gastos/}).click();await s.page.getByRole('heading',{name:'Ya están cargados',exact:true}).waitFor();await noError(s);});
 await probe('UI-09','Guardar gasto con fallo conserva formulario y permite reintentar',async()=>{const s=await setup();await addExpense(s);s.state.failNext='/api/gastos';await s.page.getByRole('button',{name:'Guardar gasto',exact:true}).click();await s.page.getByRole('status').filter({hasText:'Error de prueba'}).waitFor();assert.equal(await s.page.locator('#expense-concept').inputValue(),'Seguro de prueba');await s.page.getByRole('button',{name:'Guardar gasto',exact:true}).click();await s.page.waitForFunction(()=>document.querySelector('#expense-concept').value==='');assert.equal(s.state.db.filter(m=>m.concepto_manual==='Seguro de prueba').length,1);await noError(s);});
 await probe('UI-10','Fallo al refrescar después de guardar no invita a duplicar',async()=>{const s=await setup();await addExpense(s);s.state.failReadAfterWrite=true;await s.page.getByRole('button',{name:'Guardar gasto',exact:true}).click();await s.page.getByRole('status').filter({hasText:'El cambio se guardó'}).waitFor();assert.equal(await s.page.locator('#expense-concept').inputValue(),'');assert.equal(s.state.db.filter(m=>m.concepto_manual==='Seguro de prueba').length,1);await noError(s);});
 await probe('UI-11','Edición fallida conserva valores y muestra error en el diálogo',async()=>{const s=await setup();await nav(s.page,'Movimientos');await s.page.locator('.movement-row').filter({hasText:'Luz'}).getByRole('button',{name:'Editar',exact:true}).click();await s.page.getByRole('dialog').locator('#expense-amount').fill('16000');s.state.failNext='/api/gastos-update';await s.page.getByRole('button',{name:'Guardar cambios',exact:true}).click();await s.page.getByRole('dialog').getByRole('alert').waitFor();assert.equal(await s.page.getByRole('dialog').locator('#expense-amount').inputValue(),'16000');await s.page.keyboard.press('Escape');await s.page.getByRole('dialog').waitFor({state:'hidden'});await noError(s);});
 await probe('UI-12','Cerrar sesión limpia datos y borradores antes de otro usuario',async()=>{const s=await setup();await addExpense(s,'Borrador privado');await nav(s.page,'Ajustes');await s.page.getByRole('button',{name:'Cerrar sesión',exact:true}).click();await s.page.locator('.ob').getByRole('button',{name:'Cerrar sesión',exact:true}).click();await s.page.locator('#login-user').waitFor();assert.equal(await s.page.evaluate(()=>localStorage.getItem('gapp_v7')),null);s.state.db=[];await s.page.locator('#login-user').fill('otra');await s.page.locator('#login-pin').fill('clave-prueba');await s.page.getByRole('button',{name:'Ingresar',exact:true}).click();await s.page.getByText('Hola, Otra cuenta. Este es tu resumen.',{exact:true}).waitFor();await nav(s.page,'Cargar');assert.equal(await s.page.locator('#expense-concept').inputValue(),'');assert.equal(await s.page.getByText('Borrador privado',{exact:true}).count(),0);await noError(s);});
 await probe('UI-13','Sin mes anterior o sin mes actual: comparación sin porcentajes ficticios',async()=>{const s=await setup({records:initial().filter(m=>m.periodo==='2026-10')});await nav(s.page,'Informes');await s.page.getByText(/Sin registros en Septiembre 2026/).waitFor();assert.equal(await s.page.locator('.month-comparison').count(),0);await s.page.getByRole('button',{name:'Mes siguiente',exact:true}).click();await s.page.getByText('Todavía no hay registros en el mes seleccionado.',{exact:true}).waitFor();await noError(s);});
 await probe('UI-14','Réplica entre enero y febrero ajusta día y fecha al mes corto',async()=>{const s=await setup({clock:'2027-01-31T12:00:00-03:00',records:[expense('jan','Servicio fin de mes',5000,'2027-01',{dia:31,vencimiento:'2027-01-31',es_recurrente:true,instrumento_id:'ins_debito_automatico',instrumento_nombre:'Débito automático',forma_pago_nombre:'Débito automático'})]});await s.page.getByRole('button',{name:/Replicar gastos/}).click();await s.page.getByRole('button',{name:/Continuar con 1/}).click();await s.page.getByRole('button',{name:'Confirmar copia',exact:true}).click();await s.page.getByRole('heading',{name:'1 gasto copiado',exact:true}).waitFor();const copy=s.state.db.find(m=>m.periodo==='2027-02');assert.equal(copy.dia,28);assert.equal(copy.vencimiento,'2027-02-28');assert.equal(copy.instrumento_id,'ins_debito_automatico');assert.equal(copy.estado,'pendiente');await noError(s);});
 await probe('UI-15','Exportación completa del usuario mantiene todos sus meses',async()=>{const s=await setup();await nav(s.page,'Ajustes');await s.page.getByRole('button',{name:'Copias y datos',exact:true}).click();const downloaded=s.page.waitForEvent('download');await s.page.getByRole('button',{name:'Descargar movimientos (.json)',exact:true}).click();const download=await downloaded;const backup=JSON.parse(await fs.readFile(await download.path(),'utf8'));assert.equal(backup.usuarioId,user.usuarioId);assert.equal(backup.data.gastos['2026-10'].length,4);assert.equal(backup.data.gastos['2026-09'].length,4);await noError(s);});
 await probe('UI-16','Validación de importe, fecha pendiente y día evita escrituras incompletas',async()=>{const s=await setup();await addExpense(s,'Sin fecha',true);await s.page.locator('#expense-due').fill('');await s.page.getByRole('button',{name:'Guardar gasto',exact:true}).click();await s.page.getByRole('status').filter({hasText:'Agregá una fecha'}).waitFor();assert.equal(s.state.requests.filter(r=>r.path==='/api/gastos').length,0);await s.page.getByRole('checkbox',{name:/Revisar después/}).check();await s.page.locator('#expense-amount').fill('0');await s.page.getByRole('button',{name:'Guardar gasto',exact:true}).click();assert.equal(s.state.requests.filter(r=>r.path==='/api/gastos').length,0);await s.page.locator('#expense-amount').fill('8000');await s.page.locator('#expense-day').fill('32');await s.page.getByRole('button',{name:'Guardar gasto',exact:true}).click();assert.equal(s.state.requests.filter(r=>r.path==='/api/gastos').length,0);await noError(s);});
 await probe('UI-17','Débito automático elegido por forma o concepto inicia pendiente',async()=>{catalogos.conceptos.push({concepto_id:'auto_concept',nombre:'Suscripción de prueba',medio_pago_id:'mp_bancon',instrumento_id:'ins_debito_automatico',moneda_default:'ARS'});try{const s=await setup();await nav(s.page,'Cargar');await s.page.locator('#expense-method').selectOption('ins_debito_automatico');assert.equal(await s.page.getByRole('button',{name:'Pendiente',exact:true}).getAttribute('aria-pressed'),'true');await s.page.getByRole('checkbox',{name:/Débito automático/}).uncheck();await s.page.getByRole('button',{name:'Pagado',exact:true}).click();await s.page.locator('#expense-concept').fill('Suscripción');await s.page.getByRole('button',{name:'Suscripción de prueba',exact:true}).click();assert.equal(await s.page.getByRole('button',{name:'Pendiente',exact:true}).getAttribute('aria-pressed'),'true');assert.equal(await s.page.getByRole('checkbox',{name:/Débito automático/}).isChecked(),true);assert.equal(s.state.requests.filter(r=>r.path==='/api/gastos').length,0);await noError(s);}finally{catalogos.conceptos=[];}});
 await browser.close();await server.close();if(results.some(r=>r.status==='fallo'))process.exitCode=1;
})().catch(async e=>{console.error(e);if(browser)await browser.close();if(server)await server.close();process.exitCode=1;});
